--- #YAML:1.0
name:               Tk-Pod
version:            0.9941_50
abstract:           Pod browser widget for Tk
author:
    - Slaven Rezic <srezic@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Spec:   0
    File::Temp:   0
    Pod::Simple:  2.05
    Tk:           800.004
resources:
    repository:  git://github.com/eserte/tk-pod.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
optional_features:
    debugging:
        description:  Debugging and development helper
        requires:
            Devel::Hide:      0
            Module::Refresh:  0
            Tk::WidgetDump:   0
    external_links:
        description:  support for links using an external browser
        requires:
            URI::Escape:  0
    fulltext_search:
        description:  Enable the full-text search
        requires:
            Text::English:  0
    gzip_support:
        description:  gzip support in tkmore
        requires:
            PerlIO::gzip:  0
    nicer_gui:
        description:  Provide a nicer GUI
        requires:
            Tk::HistEntry:  0.4
            Tk::ToolBar:    0
