---
abstract: 'Pod browser widget for Tk'
author:
  - 'Slaven Rezic <srezic@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tk-Pod
no_index:
  directory:
    - t
    - inc
optional_features:
  debugging:
    description: 'Debugging and development helper'
    requires:
      Devel::Hide: 0
      Module::Refresh: 0
      Tk::WidgetDump: 0
  external_links:
    description: 'support for links using an external browser'
    requires:
      URI::Escape: 0
  fulltext_search:
    description: 'Enable the full-text search'
    requires:
      Text::English: 0
  gzip_support:
    description: 'gzip support in tkmore'
    requires:
      PerlIO::gzip: 0
  nicer_gui:
    description: 'Provide a nicer GUI'
    requires:
      Tk::HistEntry: 0.4
      Tk::ToolBar: 0
requires:
  File::Spec: 0
  File::Temp: 0
  Pod::Simple: 2.05
  Tk: 800.004
resources:
  repository: git://github.com/eserte/tk-pod.git
version: 0.9940_50
